PARTICIPANTS:
  - Sean, email@gmail.com
  - Maddie, email@gmail.com
  - Brien, email@gmail.com
  - Guy, email@gmail.com
  
DO-NOT-MATCH:
  - Maddie, Brien
  
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
USERNAME: "your email"
PASSWORD: "your pwd"
FROM: "you@gmail.com"
SUBJECT: "Secret Santa Assignment 2019"

BODY:
  Dear {santa},

  
  This year you are {santee}'s Secret Santa! Ho! Ho! Ho! and a bottle of rum!

  
  The maximum spending limit is $25.00

  
  Now Geaux out and buy something Real Nice.

  Love,
  secret-santa.py, your holiday robot overlord.